version: '3'
services:
  flask:
    container_name: backend-flask
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/Flaskex"

  nginx:
    image: nginx:alpine
    container_name: nginx-flask
    restart: unless-stopped
    ports:
      - 5000:8081
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
